# FILE: backend-nusacare/app.py (FINAL & LENGKAP)

import os
import json
from flask import Flask, jsonify, request
from flask_cors import CORS
from flask_cors import cross_origin

# Import modul RAG
from rag_module import generate_recommendation
from blockchain_service import CONTRACT_INSTANCE, w3, BACKEND_SERVICE_ADDRESS, BACKEND_PRIVATE_KEY

# ------------------------------------------------------------------
# ASUMSI DATA (Dummy untuk pengujian alur end-to-end)
# ------------------------------------------------------------------
PATIENT_DATA = {
    "P001": {
        "patient_name": "Maria",
        "medical_history": ["Alergi Debu", "Hipertensi Ringan"],
        "vitals": {
            "Temperature": 36.5,
            "BloodPressure": "130/85"
        },
        "patient_address": "0xUserBlockchainAddress"
    }
}

# ------------------------------------------------------------------
# KONFIGURASI FLASK
# ------------------------------------------------------------------
app = Flask(__name__)
CORS(app, resources={r"/api/*": {
    "origins": ["http://localhost:3000"],
    "methods": ["GET", "POST", "OPTIONS"],
    "allow_headers": ["Content-Type", "Authorization"]
}})

# ------------------------------------------------------------------
# ENDPOINT: GENERATE REKOMENDASI (RAG + LLM)
# ------------------------------------------------------------------
@app.route('/api/recommend', methods=['POST'])
def recommend_endpoint():
    try:
        data = request.get_json()

        # Data dari frontend
        patient_address = data.get('patient_id')
        symptom_label = data.get('symptom_label')
        condition_label = data.get('condition_label', 'Normal')

        if not patient_address or not symptom_label:
            return jsonify({
                "status": "error",
                "message": "Missing patient_id or symptom_label"
            }), 400

        # Context untuk RAG (TANPA P001, TANPA patient_info)
        context_data = {
            "patient_name": "Pasien Blockchain",
            "medical_history": [],
            "vitals": {},
            "patient_address": patient_address,
            "patient_query": f"Keluhan: {symptom_label}, Kondisi: {condition_label}"
        }

        # Panggil RAG
        recommendation_text = generate_recommendation(context_data)

        return jsonify({
            "status": "success",
            "recommendation": {
                "recommendation_text": recommendation_text,
                "patient_name": context_data["patient_name"],
                "timestamp": "Generated by LLM-RAG System"
            }
        }), 200

    except Exception as e:
        print(f"[RAG ERROR] {e}")
        return jsonify({
            "status": "error",
            "message": str(e)
        }), 500

# ------------------------------------------------------------------
# ENDPOINT: REGISTRASI USER (PATIENT / DOCTOR / HERBALIST)
# ------------------------------------------------------------------
@app.route('/api/register', methods=['POST'])
def register_user():
    try:
        data = request.get_json()
        wallet_address = data.get("walletAddress")
        role = data.get("role")

        if not wallet_address or not role:
            return jsonify({
                "status": "error",
                "message": "walletAddress dan role wajib diisi"
            }), 400

        print(f"[REGISTER] Wallet={wallet_address}, Role={role}")

        return jsonify({
            "status": "success",
            "message": "Registrasi berhasil"
        }), 200

    except Exception as e:
        print(f"[REGISTER ERROR] {e}")
        return jsonify({
            "status": "error",
            "message": "Internal Server Error"
        }), 500

# ------------------------------------------------------------------
# ENDPOINT: LOGIN (SIMULASI ROLE)
# ------------------------------------------------------------------
@app.route('/api/login', methods=['POST'])
def login_user():
    try:
        data = request.get_json()
        wallet_address = data.get("walletAddress")

        if not wallet_address:
            return jsonify({"status": "error", "message": "walletAddress wajib diisi"}), 400

        # Ambil data asli dari Blockchain melalui service
        from blockchain_service import get_patient_record
        user_record = get_patient_record(wallet_address)

        if not user_record:
             return jsonify({"status": "error", "message": "Akun tidak terdaftar di Blockchain"}), 404

        # Ambil role asli (patient/herbal/medis/admin) dari record
        user_role = user_record.get("role", "patient") 

        print(f"[LOGIN] Wallet={wallet_address}, Role={user_role}")

        return jsonify({
            "status": "success",
            "role": user_role  # Mengembalikan role dinamis dari Blockchain
        }), 200
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500
    
import traceback # Tambahkan di bagian paling atas file

@app.route('/api/herbal/add', methods=['POST', 'OPTIONS'])
@cross_origin()
def add_herbal_knowledge():
    if request.method == 'OPTIONS':
        return '', 200
        
    try:
        data = request.get_json()
        wallet = data.get('herbalist_wallet')
        herbal_name = data.get('name')

        print(f"--- PROSES BARU: {herbal_name} ---")

        # 1. IPFS Upload
        from ipfs_service import upload_to_ipfs
        herbal_cid = upload_to_ipfs(data, is_encrypted=True)

        if not herbal_cid:
            print("❌ STOP: IPFS gagal memberikan CID.")
            return jsonify({"status": "error", "message": "Gagal ke IPFS. Cek IPFS Desktop!"}), 503

        print(f"✅ IPFS Success: {herbal_cid}")

        # 2. BLOCKCHAIN
        from blockchain_service import CONTRACT_INSTANCE, w3, BACKEND_SERVICE_ADDRESS, BACKEND_PRIVATE_KEY
        
        # Validasi Alamat Wallet
        try:
            valid_wallet = w3.to_checksum_address(wallet)
        except:
            return jsonify({"status": "error", "message": f"Wallet {wallet} tidak valid formatnya"}), 400
        
        # Kirim Transaksi
        print("Mencoba kirim ke Blockchain...")
        txn = CONTRACT_INSTANCE.functions.registerUser(
            valid_wallet,
            herbal_name,
            "2025-12-20",
            str(herbal_cid), # Pastikan CID adalah String
            "aes_key", 
            "pass_key", 
            "Doctor"
        ).build_transaction({
            'from': BACKEND_SERVICE_ADDRESS,
            'nonce': w3.eth.get_transaction_count(BACKEND_SERVICE_ADDRESS),
            'gas': 1000000,
            'gasPrice': w3.eth.gas_price
        })

        signed_txn = w3.eth.account.sign_transaction(txn, private_key=BACKEND_PRIVATE_KEY)
        tx_hash = w3.eth.send_raw_transaction(signed_txn.raw_transaction)
        w3.eth.wait_for_transaction_receipt(tx_hash)
        print(f"✅ Blockchain Success: {tx_hash.hex()}")

        # 3. CHROMA
        from rag_initialization import add_to_chroma
        add_to_chroma(data)

        return jsonify({
            "status": "success", 
            "cid": herbal_cid, 
            "blockchain_tx": tx_hash.hex()
        }), 200

    except Exception as e:
        # INI AKAN MENAMPILKAN ERROR ASLINYA DI TERMINAL VS CODE
        print("❌ ERROR DETAIL DI TERMINAL:")
        traceback.print_exc() 
        return jsonify({"status": "error", "message": str(e)}), 500
# ------------------------------------------------------------------
# STATUS SERVER
# ------------------------------------------------------------------
@app.route('/api/status', methods=['GET'])
def status_endpoint():
    return jsonify({
        "status": "running",
        "model": "Gemma 3 + RAG"
    }), 200

# ------------------------------------------------------------------
# MAIN LOOP
# ------------------------------------------------------------------
if __name__ == "__main__":
    port = int(os.getenv("APP_PORT", 4002))
    app.run(host="0.0.0.0", port=port, debug=False)
