# FILE: backend-nusacare/app.py (FINAL LENGKAP)

import os # Diperlukan untuk membaca APP_PORT dari .env
import json # Diperlukan untuk memproses JSON
from flask import Flask, jsonify, request # Tambahkan 'request' untuk menangani POST data
from flask_cors import CORS

# Import modul RAG
from rag_module import generate_recommendation

# --- ASUMSI DATA (Contoh Dummy Data/Context) ---
# Biasanya ini didapatkan dari database atau dari request, tapi diperlukan untuk menguji alur.
PATIENT_DATA = {
    "P001": {
        "patient_name": "Maria",
        "medical_history": ["Alergi Debu", "Hipertensi Ringan"],
        "vitals": {"Temperature": 36.5, "BloodPressure": "130/85"},
        "patient_address": "0xUserBlockchainAddress" # Diperlukan untuk Blockchain
    }
}

# --- KONFIGURASI APLIKASI FLASK ---
app = Flask(__name__) 
CORS(app) # Mengaktifkan CORS untuk interaksi Frontend

# --- ENDPOINT UTAMA ---
@app.route('/api/recommend', methods=['POST'])
def recommend_endpoint():
    
    # 1. Validasi Data Masuk
    try:
        # Asumsi request POST berisi data query dan ID pasien
        data = request.get_json()
        patient_id = data.get('patient_id', 'P001') # Default untuk pengujian
        query_text = data.get('query', 'Saya sakit kepala dan susah tidur.')
    except Exception:
        return jsonify({"status": "error", "message": "Invalid JSON format."}), 400

    # 2. Retrieval info pasien
    patient_info = PATIENT_DATA.get(patient_id)
    if not patient_info:
        return jsonify({"status": "error", "message": "Patient ID not found."}), 404

    # Gabungkan semua data konteks yang dibutuhkan oleh rag_module
    context_data = {
        "patient_name": patient_info['patient_name'],
        "medical_history": patient_info['medical_history'],
        "vitals": patient_info['vitals'],
        "patient_address": patient_info['patient_address'],
        "patient_query": query_text
    }
    
    # 3. Panggil Logika RAG
    try:
        # Panggilan ke rag_module (yang akan memproses RAG, IPFS, dan Blockchain)
        recommendation_text = generate_recommendation(context_data) 
        
        # 4. Kembalikan Hasil
        return jsonify({
            "status": "success",
            "recommendation": {
                "recommendation_text": recommendation_text,
                "timestamp": "Generated by LLM/RAG",
                "patient_name": context_data['patient_name']
            }
        }), 200

    except Exception as e:
        # Jika terjadi error selama RAG/Blockchain/LLM
        print(f"Internal RAG/Blockchain Error: {e}")
        return jsonify({
            "status": "error", 
            "message": f"Recommendation generation failed: {str(e)}"
        }), 500

@app.route('/api/register', methods=['POST'])
def register_user():
    try:
        data = request.get_json()
        wallet_address = data.get('walletAddress')
        role = data.get('role')
        
        if not wallet_address or not role:
            return jsonify({"status": "error", "message": "Missing walletAddress or role"}), 400

        # --- TODO: Di sini nanti dimasukkan logic Smart Contract untuk mencatat ID pengguna ---
        # Untuk saat ini, hanya mencatat ke log server
        print(f"\n[REGISTRATION SUCCESS LOG] Role: {role}, Wallet: {wallet_address}\n")
        
        # Respons sukses agar frontend bisa lanjut (redirect)
        return jsonify({"status": "success", "message": "Registration successful"}), 200

    except Exception as e:
        print(f"ERROR during registration: {e}")
        return jsonify({"status": "error", "message": "Internal Server Error during registration"}), 500
    
# FILE: backend-nusacare/app.py (TAMBAHKAN KODE INI)

@app.route('/api/login', methods=['POST'])
def login_user():
    try:
        data = request.get_json()
        wallet_address = data.get('walletAddress')
        
        if not wallet_address:
            return jsonify({"status": "error", "message": "Missing walletAddress"}), 400

        # --- Simulasi Verifikasi (Selalu Sukses untuk Uji Coba) ---
        # Di sini Anda akan mencari user di database dan mendapatkan role-nya.
        user_role = "patient" # Default role untuk uji coba
        
        print(f"\n[LOGIN SUCCESS LOG] Wallet: {wallet_address}, Role: {user_role}\n")
        
        # Respons sukses, mengembalikan role ke frontend
        return jsonify({"status": "success", "role": user_role}), 200

    except Exception as e:
        print(f"ERROR during login: {e}")
        return jsonify({"status": "error", "message": "Internal Server Error during login"}), 500

# --- UTILITY ENDPOINTS (Opsional) ---
@app.route('/api/status', methods=['GET'])
def status_endpoint():
    """Endpoint untuk mengecek apakah server berjalan."""
    return jsonify({"status": "running", "model": "Gemma 7B (Base)"}), 200


# --- FLASK MAIN LOOP (PENTING!) ---
if __name__ == '__main__':
    # Dapatkan port dari .env, default ke 4001
    port = int(os.getenv("APP_PORT", 5050)) 
    
    # Jalankan aplikasi. host='0.0.0.0' memungkinkan akses dari jaringan luar.
    app.run(host='0.0.0.0', port=port, debug=False)